# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class STWBerlinMenuServiceStub(object):
  """Service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMenu = channel.unary_unary(
        '/STWBerlinMenuService/GetMenu',
        request_serializer=service__pb2.MenuRequest.SerializeToString,
        response_deserializer=service__pb2.MenuResult.FromString,
        )
    self.GetPictograms = channel.unary_unary(
        '/STWBerlinMenuService/GetPictograms',
        request_serializer=service__pb2.PictogramRequest.SerializeToString,
        response_deserializer=service__pb2.PictogramResult.FromString,
        )
    self.GetDiningFacilityCodes = channel.unary_unary(
        '/STWBerlinMenuService/GetDiningFacilityCodes',
        request_serializer=service__pb2.DiningFacilityCodesRequest.SerializeToString,
        response_deserializer=service__pb2.DiningFacilityCodesResult.FromString,
        )


class STWBerlinMenuServiceServicer(object):
  """Service
  """

  def GetMenu(self, request, context):
    """Get multiple
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPictograms(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDiningFacilityCodes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_STWBerlinMenuServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMenu': grpc.unary_unary_rpc_method_handler(
          servicer.GetMenu,
          request_deserializer=service__pb2.MenuRequest.FromString,
          response_serializer=service__pb2.MenuResult.SerializeToString,
      ),
      'GetPictograms': grpc.unary_unary_rpc_method_handler(
          servicer.GetPictograms,
          request_deserializer=service__pb2.PictogramRequest.FromString,
          response_serializer=service__pb2.PictogramResult.SerializeToString,
      ),
      'GetDiningFacilityCodes': grpc.unary_unary_rpc_method_handler(
          servicer.GetDiningFacilityCodes,
          request_deserializer=service__pb2.DiningFacilityCodesRequest.FromString,
          response_serializer=service__pb2.DiningFacilityCodesResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'STWBerlinMenuService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
